general:
  cpiApiServiceKeyCredentialsId: "desgauthapikey"
  integrationFlowId: "calling iflows from other cpi account Created"
stages:
  Upload:
    enabled: true
  Deploy:
    enabled: false
  Integration Test:
    enabled: false
steps:
  integrationArtifactUpload:
    packageId: "devtenantcicd"
    integrationFlowName: " calling iflows from other cpi account Created"
